### PR TITLE
verify PVs and SAs

### PR DESCRIPTION
**Pull request by bdecoste**
Fail test if the template requires 1) a PV that doesn't exist or 2) an SA that doesn't exist

Also delete the environment if there is such a failure

### CODE REVIEW

**Comment by alesj** [comment]
@bdecoste you shouldn't mix OpenShift adapter code with HttpClient abstraction.
OpenShift adapters should already have a way to get all that info.

Let me see if I can easily re-write this ...

**Comment by alesj** [comment]
@bdecoste can you check if this works for you:
* https://github.com/alesj/ce-arq/tree/bd1

(I removed the need for http-client in adapters, etc)

**Comment by bdecoste** [comment]
Thanks. The F8OpenShiftAdapter client is set to the test's namespace so it never finds any PVs - the call is going to /api/v1/namespaces/cearq-ds-fzjkxwlh504/persistentvolumes instead of /api/v1/persistentvolumes

I'll see if I can fix this and put in a PR against your branch.

**Comment by bdecoste** [comment]
https://github.com/alesj/ce-arq/pull/2

**Pull request merged**
